<?xml version="1.0" ?>
<!-- kinect(parent-link must be base-link) -->
<robot name="kinect" xmlns:xacro="http://www.ros.org/wiki/xacro">
    <!-- //////////////////////////    INCLUDE   //////////////////////////// -->
    <xacro:include filename="$(find myRobotGazebo)/urdf/props/const-props.xacro" />
    <!-- pedestal -->
    <xacro:include filename="$(find myRobotGazebo)/urdf/component/pedestal-gazebo.xacro" />

    <xacro:macro name="kinect_link">
        <link name="kinect_link">
            <visual>
                <origin xyz="0 0 0" rpy="0 0 ${PI / 2}"/>
                <geometry>
                    <mesh filename="package://myRobot/meshes/kinect.dae" />
                </geometry>
            </visual>
        </link>

        <joint name="kinect_joint" type="fixed">
            <origin xyz="0 0 ${pedestal_length + pedestal_floor_distan}" rpy="0 0 0"/>
            <parent link="base_link"/>
            <child link="kinect_link"/>
        </joint>

        <!-- set link as camera -->
        <gazebo reference="kinect_link">  
            <sensor type="depth" name="camera">
                <always_on>true</always_on>
                <update_rate>20.0</update_rate>
                <camera>
                    <horizontal_fov>${60.0*PI/180.0}</horizontal_fov>
                    <image>
                        <format>R8G8B8</format>
                        <width>640</width>
                        <height>480</height>
                    </image>
                    <clip>
                        <near>0.05</near>
                        <far>8.0</far>
                    </clip>
                </camera>
                <plugin name="kinect_camera_controller" filename="libgazebo_ros_openni_kinect.so">
                    <cameraName>camera</cameraName>
                    <alwaysOn>true</alwaysOn>
                    <updateRate>10</updateRate>
                    <imageTopicName>rgb/image_raw</imageTopicName>
                    <depthImageTopicName>depth/image_raw</depthImageTopicName>
                    <pointCloudTopicName>depth/points</pointCloudTopicName>
                    <cameraInfoTopicName>rgb/camera_info</cameraInfoTopicName>
                    <depthImageCameraInfoTopicName>depth/camera_info</depthImageCameraInfoTopicName>
                    <frameName>kinect_link</frameName>
                    <baseline>0.1</baseline>
                    <distortion_k1>0.0</distortion_k1>
                    <distortion_k2>0.0</distortion_k2>
                    <distortion_k3>0.0</distortion_k3>
                    <distortion_t1>0.0</distortion_t1>
                    <distortion_t2>0.0</distortion_t2>
                    <pointCloudCutoff>0.4</pointCloudCutoff>
                </plugin>
            </sensor>
        </gazebo>
    </xacro:macro>
</robot>