<?xml version="1.0" ?>
<!-- laser(parent-link must be base-link) -->
<robot name="laser" xmlns:xacro="http://www.ros.org/wiki/xacro">
    <!-- //////////////////////////    INCLUDE   //////////////////////////// -->
    <xacro:include filename="$(find myRobotGazebo)/urdf/props/color-props.xacro" />
    <xacro:include filename="$(find myRobotGazebo)/urdf/props/const-props.xacro" />
    <xacro:include filename="$(find myRobotGazebo)/urdf/props/imatrix-props.xacro" />
    <!-- pedestal -->
    <xacro:include filename="$(find myRobotGazebo)/urdf/component/pedestal-gazebo.xacro" />

    <!-- laser-props -->
    <xacro:property name="laser_radius" value="0.05" />
    <xacro:property name="laser_length" value="0.05" />
    <xacro:property name="laser_mass" value="0.15" />

    <!-- laser macro -->
    <xacro:macro name="laser_link">
        <link name="laser_link">
            <!-- visual-props -->
            <visual>
                <origin xyz=" 0 0 0 " rpy="0 0 0" />
                <geometry>
                    <cylinder length="${laser_length}" radius="${laser_radius}"/>
                </geometry>
                <Black />
            </visual>
            <!-- collsion-props -->
            <collision>
            <origin xyz="0 0 0" rpy="${PI / 2} 0 0" />
            <geometry>
                <cylinder radius="${laser_radius}" length = "${laser_length}"/>
            </geometry>
            </collision>
            <!-- dynamic-props -->
            <xacro:cylinder_inertial_matrix m="${laser_mass}" r="${laser_radius}"
                                            h="${laser_length}" />
        </link>

        <joint name="laser_joint" type="fixed">
            <origin xyz="${- pedestal_radius / 1.5} 0 ${pedestal_length + pedestal_floor_distan}" rpy="0 0 0"/>
            <parent link="base_link"/>
            <child link="laser_link"/>
            <axis xyz="0 0 1" />
        </joint>

        <!-- color -->
        <gazebo reference="laser_link">
            <material>Gazebo/Black</material>
        </gazebo>

        <!-- transmission -->
        <transmission name="$laser_link_trans">
            <type>transmission_interface/SimpleTransmission</type>
            <joint name="$laser_link_trans_joint" >
                <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
            </joint>
            <actuator name="$laser_link_trans_motor">
                <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
                <mechanicalReduction>1</mechanicalReduction>
            </actuator>
        </transmission>
        <!-- laser plugin -->
        <gazebo reference="laser_link">
            <sensor type="ray" name="rplidar">
            <pose>0 0 0 0 0 0</pose>
            <visualize>true</visualize>
            <update_rate>5.5</update_rate>
            <ray>
                <scan>
                <horizontal>
                    <samples>360</samples>
                    <resolution>1</resolution>
                    <min_angle>-3</min_angle>
                    <max_angle>3</max_angle>
                </horizontal>
                </scan>
                <range>
                <min>0.10</min>
                <max>30.0</max>
                <resolution>0.01</resolution>
                </range>
                <noise>
                <type>gaussian</type>
                <mean>0.0</mean>
                <stddev>0.01</stddev>
                </noise>
            </ray>
            <plugin name="gazebo_rplidar" filename="libgazebo_ros_laser.so">
                <topicName>/scan</topicName>
                <frameName>laser</frameName>
            </plugin>
            </sensor>
        </gazebo>
    </xacro:macro>
</robot>